name: Danny Yang
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
highlighter: rouge
plugins:
  - jekyll-feed
author: Danny Yang
title: Danny Yang's Blog
description: A blog mostly about compilers, programming languages, and data vis.
feed:
  posts_limit: 100